### ISSUE TITLE
How can I declare a huge number of execution environments?

### ISSUE THREAD

**Issue by MaddyGuthridge** [DetachHead/basedpyright#1042]
Hello, and thanks for all your work maintaining this awesome library!

I maintain the course content for [UNSW's COMP1010 course](https://github.com/COMP1010UNSW/) and am in the process of introducing type safety checks to the CI of our course content repo (private because we don't want to leak exam solutions, etc).

The issue I have encountered is that we get tons of `reportImplicitRelativeImport` errors. This happens because every single exercise is essentially its own Python project.

```sh
| maddy@yzma :: ~/Source/COMP/1010/course-content (main) ⚡ 
⋙   tree content -L 3 -d 
content
├── exams
│   ├── chess
│   │   ├── solution
│   │   ├── spec
│   │   └── starter
│   ├── ...8 other exams
├── labs
│   ├── bug_hunt
│   │   ├── marking
│   │   ├── solution
│   │   └── starter
│   ├── ...30 other lab exercises
├── project
├── tutorials
│   ├── tutorial_01
│   │   ├── solution
│   │   └── starter
│   ├── ...8 other weekly tutorials
└── wip

168 directories
```

What I'm looking for is a way to declare each of these directories as its own `executionEnvironment`, where they all share the same configuration (perhaps giving a couple of them simple overrides).

Ideally, I would be able to declare a list of roots, rather than a single root, and perhaps use globs to select many directories; with each directory existing as its own execution environment using the given rules:

```toml
# pyproject.toml
[[tool.basedpyright.executionEnvironments]]
root = [
    "content/labs/*/starter",
    "content/tutorials/*/starter",
]
# ... rules for starter code


[[tool.basedpyright.executionEnvironments]]
root = [
    "content/labs/*/solution",
    "content/tutorials/*/solution",
]
# ... slightly more-strict rules for solution code


[[tool.basedpyright.executionEnvironments]]
root = "content/labs/*/marking"
# ... very strict rules for marking code, because we don't want any bugs in our auto-marking

# etc
```

Is there a way that I can accomplish this using BasedPyright? If so, how can I do it?

**Comment by DetachHead** [comment]
glad to hear basedpyright is being used in uni courses! 

putting a `pyproject.toml` in each project directory could be an alternative approach
```toml
# content/labs/*/starter/pyproject.toml
extends = "../../../pyproject.toml"
```

but i don't think that works properly with the language server iirc

supporting globs sounds like a good idea though. in the mean time you might have to just disable that rule unfortunately 
```toml
[tool.basedpyright]
reportImplicitRelativeImport = false
```
