### ISSUE TITLE
Override diagnostic severities for directory

### ISSUE THREAD

**Issue by disrupted** [DetachHead/basedpyright#1114]
### Description

How can I configure the reported diagnostics for a specific folder?

At the moment I am abusing execution environments for it, but I guess that's not how they are intended to be used.

E.g. I want to silence some warnings only in tests
```toml
[[tool.basedpyright.executionEnvironments]]
root = "tests"
reportPrivateUsage = false
reportUnusedParameter = false
reportUnusedCallResult = false
reportDeprecated = "hint"
```

but I noticed that this breaks the module path of import suggestions inside tests, because it now believes "tests" is the root.
