### ISSUE TITLE
code action import suggestions don't work if `reportUndefinedVariable` is disabled

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#121]

**Comment by DetachHead** [comment]
i dont think it's possible, nor does it make sense to add a quick to an error that's not enabled and not being reported.

the use case for this was when using basedpyright for the language server and another type checker like basedmypy for the type checking. but to fix this issue you can just switch to basedpyright for that specific rule:

```toml
# pyproject.toml
[tool.mypy]
disable_error_code = ["name-defined"]

[tool.basedpyright]
typeCheckingMode = "off"
reportUndefinedVariable = true
```
