### ISSUE TITLE
[config] extends field with absolute path does not support home expansion ("~") but "/Users/user" works.

### ISSUE THREAD

**Issue by BlueDruddigon** [DetachHead/basedpyright#1309]
### Description

I've been using pyproject.toml for python project configuration.
This is my global configuration:

```toml
[tool.basedpyright]
typeCheckingMode = "basic"
useLibraryCodeForTypes = true

reportUnusedImport = false
```

And for an example Python project, I have this config:
```toml
[tool.basedpyright]
extends = "~/.config/pyproject.toml"  # this line does not work
# extends = "/Users/user/.config/pyproject.toml"  # enable this line, it works
```
However, that configuration didn't load the global pyproject.toml.
When I switch from home expansion ("~") to "/Users/user", the pyproject.toml works fine.

Is this a bug? Since, along with the basedpyright tool, i've been using ruff as well, and configuring "~" in the `extend` field works like a charm.

The core reason that I prefer home expansion over the full absolute path is that I want to avoid user leaks to the internet (i.e., pushing the codebase to GitHub).

Could I request a feature implementation for this?
