### ISSUE TITLE
Regression (1.29.2 -> 1.29.3): "unknown config option: reportUnreachable"

### ISSUE THREAD

**Issue by inducer** [DetachHead/basedpyright#1325]
### Description

In my `pyproject.toml`, I have
```toml
[tool.basedpyright]
# ...
reportUnreachable = "hint"
# ...
```
With 1.29.3, I get a complaint:
```
unknown config option: reportUnreachable
```
With 1.29.2, no such complaint is issued.
