### ISSUE TITLE
Language injection for parameters

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#195]
This requires two fronts: direct denotation, and config file denotation. Because we don't control everyone's src code

```py
def foo(reg: Annotated[str, basedtyping.Language["regex"]): ...
# or
def f(
    # language=regex
    reg: str
): ...
```
For third party code
```toml
[[tool.basedpyright.language-injections]]
function = "re.search"
parameter = "pattern"
language= "regex"
```
