### ISSUE TITLE
Github action

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#238]
Maybe we can fork/update https://github.com/jakebailey/pyright-action to support basedpyright

Additionally, the docs for this were deleted.

**Comment by DetachHead** [comment]
what does it do that this doesn't?

```yaml

jobs:
  static_checks:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: ./pw run basedpyright
```
