### ISSUE TITLE
setting `pythonVersion` in `executionEnvironments` does not work with `sys.version_info` checks

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#416]
```toml
[tool.basedpyright]
pythonVersion = "3.8"
reportUnusedImport = false

[[tool.basedpyright.executionEnvironments]]
root = "foo"
pythonVersion = "3.9"
```
```py
# main.py
from typing import Sequence # no error because Sequence is not deprecated in 3.8

print("".removesuffix) # error because removesuffix doesn't exist in 3.8
```
```py
# foo/a.py
from typing import Sequence # error: This type is deprecated as of Python 3.9; use "collections.abc.Sequence"
print("".removesuffix) # error because it thinks this execution environment is in 3.8???
```
