### ISSUE TITLE
`typeCheckingMode` defaults to `"standard"` instead of `"all"` in cli due to upstream change

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#417]
```toml
# pyproject.toml

[tool.pyright]
pythonVersion = "3.12"
reportUnusedImport = false
reportDeprecated = true
```
```py
from typing import Sequence, Union
```
![image](https://github.com/DetachHead/basedpyright/assets/57028336/66e03610-7d68-4888-ade4-1303a460b8ef)

```
>basedpyright
0 errors, 0 warnings, 0 notes
```
