### ISSUE TITLE
Getting errors on basic os.system calls, are these intended?

### ISSUE THREAD

**Issue by leet0rz** [DetachHead/basedpyright#480]
Error:
```
1. basedpyright: Result of call expression is of type "int" and is not used; assign to variable "_" if this is intentional [reportUnusedCallResult]
```

Is this intended?:
https://i.imgur.com/5tVfWzG.png

**Comment by DetachHead** [comment]
all diagnostic rules are enabled by default in basedpyright so yes it is intended. [the reasoning behind this decision is explained here](https://docs.basedpyright.com/#/?id=better-defaults)

one of the use cases of `reportUnusedCallResult` is to prevent unintended suppression of errors. because `os.system` returns the exit code, that means the program will continue running even if the command fails, which often is not intended. you may instead want to check the exit code and raise an exception if it failed:

```py
result = os.system("echo hello!")
if result != 0:
    raise Exception(f"command failed with exit code {result}")
```

if it is intentional to ignore the exit code, you can either assign it to a variable called `_` like it suggests:
```py
_ = os.system("echo hello!")
```
or you can just turn off the rule if you don't like it:
```toml
# pyproject.toml
[tool.basedpyright]
reportUnusedCallResult = false
```
or if you just want to use the same defaults as upstream pyright, you can set `typeCheckingMode` to `"standard"`:

```toml
# pyproject.toml
[tool.basedpyright]
typeCheckingMode = "standard"
```
