### ISSUE TITLE
disable `enableTypeIgnoreComments` by default (ie. even when typeCheckingMode=all)

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#55]
partial workaround:
```toml
[tool.basedpyright]
enableTypeIgnoreComments = false
```
prevents `type:ignore` comments from working alltogether which can prevent actual errors from being incorrectly suppressed using an invalid code
