### ISSUE TITLE
How to debug CPU 100% issue?

### ISSUE THREAD

**Issue by failable** [DetachHead/basedpyright#659]
I like basedpyright.

I use basedpyright in small-scale projects, typically around 5000 lines of code. However, basedpyright often easily consumes all my CPU, causing the completion menu in my editor to appear very slowly, and the jump functionality becomes almost unusable. It takes several minutes after I stop editing for the CPU usage to decrease.

I'm using all the default configurations of basedpyright. I didn't encounter similar issues when I used pyright before, although I know basedpyright enables more default rules than pyright. Basedpyright always easily reaches a state of very high CPU usage.

Python version: 3.10.11

```shell
$ basedpyright --version
basedpyright 1.17.3
based on pyright 1.1.379
```

Common dependencies in my projects:

```toml
dependencies = [
    "fastapi>=0.112.0",
    "uvicorn>=0.30.5",
    "structlog>=24.4.0",
    "mysqlclient>=2.2.4",
    "aiomysql>=0.2.0",
    "polars>=1.4.1",
    "pandas>=2.2.2",
    "numpy<2",
    "pyarrow>=17.0.0",
    "async-lru>=2.0.4",
    "sqlalchemy[asyncio]>=2.0.32",
    "asyncmy>=0.2.9",
    "pydantic-settings>=2.4.0",
    "cryptography>=43.0.0",
    "setuptools>=72.2.0",
    "pillow>=10.4.0",
    "regex>=2024.7.24",
    "connectorx>=0.3.3",
    "oss2>=2.18.6",
    "httpx[socks]>=0.27.2",
    "rapidocr-onnxruntime>=1.3.24",
]
```

```toml
dependencies = [
    "fastapi>=0.111.1",
    "pydantic>=2.8.2",
    "pydantic-settings>=2.3.4",
    "httpx[socks]>=0.27.0",
    "trafilatura[all]>=1.11.0",
    "motor>=3.5.1",
    "structlog>=24.4.0",
    "pandas>=2.2.2",
    "qdrant-client>=1.11.0",
    "llm-taxi>=0.5.0",
    "mistralai==0.4.2",
]
```

Editors: 

Zed

```
Zed: v0.152.1 (Zed Preview)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: x86_64
```

VSCode

```
Version: 1.92.2 (Universal)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 23.6.0
```

**Comment by DetachHead** [comment]
a couple things to try:

- change `typeCheckingMode` to `"standard"` and see if it makes a difference
- compare with pyright with all its rules enabled:
  ```toml
  [tool.pyright]
  typeCheckingMode = "strict"
  # pyright doesn't have an "all" type checking mode so we still need to enable a bunch of them specifically:
  deprecateTypingAliases = true
  enableExperimentalFeatures = true
  reportMissingModuleSource = "error"
  reportCallInDefaultInitializer = "error"
  reportImplicitOverride = "error"
  reportImplicitStringConcatenation = "error"
  reportImportCycles = "error"
  reportMissingSuperCall = "error"
  reportPropertyTypeMismatch = "error"
  reportShadowedImports = "error"
  reportUninitializedInstanceVariable = "error"
  reportUnnecessaryTypeIgnoreComment = "error"
  reportUnusedCallResult = "error"
  ```
- does it also happen on older versions of basedpyright?
