### ISSUE TITLE
hint diagnostics that don't come from baselined errors prevent the baseline file from being automatically rewritten when running in the cli

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#720]
```toml
# pyproject.toml

[tool.basedpyright]
reportUnreachable = 'unreachable'
```
```py
# foo.py

if False:
    ... # reportUnreachable (hint, not baselined)
# _ = 1 + "" # baselined error that we just removed
```
# command
```
basedpyright
```
# expected result
```
updated ./.basedpyright/baseline.json with 1 error (went down by 1)
0 errors, 0 warnings, 0 notes
```
# actual result
```
0 errors, 0 warnings, 0 notes
```
