### ISSUE TITLE
Conda-forge?

### ISSUE THREAD

**Issue by lucascolley** [DetachHead/basedpyright#908]
Would it be possible to make this package installable via conda-forge?

The process would be to make a PR like https://github.com/conda-forge/staged-recipes/pull/27690. A script for this package generated by grayskull is 

```yaml
{% set name = "basedpyright" %}
{% set version = "1.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/basedpyright-{{ version }}.tar.gz
  sha256: 457e97ac4c3f694b900453d3f8824af36d17b9cef3d76c623e665dd4c7872d9c

build:
  entry_points:
    - basedpyright = basedpyright.pyright:main
    - basedpyright-langserver = basedpyright.langserver:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pdm-backend >=2.3.0
    - nodejs-wheel >=20.13.1
    - typing_extensions >=4.12.2
    - docify >=1.0.0
    - pip
  run:
    - python >=3.8
    - nodejs-wheel-binaries >=20.13.1

test:
  imports:
    - basedpyright
  commands:
    - pip check
    - basedpyright --help
    - basedpyright-langserver --help
  requires:
    - pip

about:
  summary: static type checking for Python (but based)
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE.txt
    - basedpyright/dist/typeshed-fallback/LICENSE
    - docstubs/LICENSE
    - packages/pyright/LICENSE.txt
    - packages/pyright/dist/typeshed-fallback/LICENSE
    - packages/pyright-internal/node_modules/@types/lodash/LICENSE
    - packages/pyright-internal/typeshed-fallback/LICENSE

extra:
  recipe-maintainers:
    - lucascolley
    - DetachHead
```

There may be some complications with the vendored packages, but I'm sure the conda-forge maintainers can help with that.
