### ISSUE TITLE
option in the language server to specify the location of `pyproject.toml`/`pyrightconfig.json`

### ISSUE THREAD

**Issue by laguill** [DetachHead/basedpyright#941]
Hello,

I am using basedpyright in vscode and basedpyright is installed in my pixi environmment.
I would like to configure basedpyright to not check for Any type.

It seams there is something wrong with my config because basepyright is still returning error `Type Any is not allowed`

```toml
[tool.pyright]
typeCheckingMode = "recommended"
reportAny = "none"
reportExplicitAny = "none"
```
