### ISSUE TITLE
Expose `pythonPath` as a configuration option

### ISSUE THREAD

**Issue by Jomik** [DetachHead/basedpyright#948]
It seems like we cannot set `pythonPath`directly in the pyproject `tool.pyright` section.
I feel like this would be useful for using a project-local venv.
Current workaround is 
```toml
[tool.pyright]
venvPath = "./"
venv = ".venv"
```
